#!/usr/bin/env node

/**
 * Pre-build script: Embed skill folders into TypeScript.
 *
 * Reads src/mcp/skills/<skill-name>/** (markdown + bundled assets like
 * rules.yaml, example .ts files) and generates
 * src/mcp/skills/embeddedSkillContent.ts.
 *
 * This ensures skill content is compiled into JavaScript by tsc, eliminating
 * the need to add .github/ files to the npm package `files` array (which
 * currently only ships README.md). At consumer init-agents time, the CLI
 * writes every skill file to the consumer's .github/skills/<skill>/<file>.
 *
 * Run: node scripts/embed-skills.js
 * Triggered automatically by: npm run build (pre-build phase).
 */

const fs = require('fs');
const path = require('path');

const skillsDir = path.join(__dirname, '..', 'src', 'mcp', 'skills');
const outputFile = path.join(skillsDir, 'embeddedSkillContent.ts');

function walk(dir, base = dir) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    const results = [];
    for (const entry of entries) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            results.push(...walk(full, base));
        } else if (entry.isFile()) {
            const rel = path.relative(base, full).replace(/\\/g, '/');
            results.push({ absPath: full, relPath: rel });
        }
    }
    return results;
}

function escapeForTemplateLiteral(content) {
    return content
        .replace(/\\/g, '\\\\')
        .replace(/`/g, '\\`')
        .replace(/\$\{/g, '\\${');
}

let output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/embed-skills.js
 * Source files: src/mcp/skills/<skill-name>/**
 *
 * Re-run "node scripts/embed-skills.js" after editing any skill file.
 * This file is automatically regenerated during "npm run build".
 */

export const SKILL_CONTENT: Record<string, Record<string, string>> = {
`;

let skillCount = 0;
let fileCount = 0;

if (!fs.existsSync(skillsDir)) {
    console.warn(`  Warning: skills dir not found: ${skillsDir}`);
    fs.writeFileSync(outputFile, output + '};\n\nexport const SKILL_NAMES: readonly string[] = [];\n', 'utf-8');
    process.exit(0);
}

const skills = fs.readdirSync(skillsDir, { withFileTypes: true })
    .filter(e => e.isDirectory())
    .map(e => e.name)
    .sort();

for (const skillName of skills) {
    const skillRoot = path.join(skillsDir, skillName);
    const files = walk(skillRoot, skillRoot);
    if (files.length === 0) continue;

    output += `    '${skillName}': {\n`;
    for (const { absPath, relPath } of files) {
        const raw = fs.readFileSync(absPath, 'utf-8');
        const normalised = raw.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
        const escaped = escapeForTemplateLiteral(normalised);
        output += `        '${relPath}': \`${escaped}\`,\n`;
        fileCount++;
    }
    output += `    },\n`;
    skillCount++;
}

output += `};\n\n`;
output += `export const SKILL_NAMES: readonly string[] = ${JSON.stringify(skills)} as const;\n`;

fs.writeFileSync(outputFile, output, 'utf-8');
console.log(`✅ Embedded ${skillCount} skills (${fileCount} files) into ${path.relative(process.cwd(), outputFile)}`);
