#!/usr/bin/env node

/**
 * Pre-build script: Embed agent .md content into TypeScript
 *
 * Reads src/mcp/agents/*.md and generates src/mcp/agents/embeddedAgentContent.ts
 * This ensures agent content is compiled into JavaScript by tsc, eliminating
 * dependency on .md files being present in the published npm package.
 *
 * Run: node scripts/embed-agents.js
 * Triggered automatically by: npm run build (pre-build phase)
 */

const fs = require('fs');
const path = require('path');

const agentsDir = path.join(__dirname, '..', 'src', 'mcp', 'agents');
const outputFile = path.join(agentsDir, 'embeddedAgentContent.ts');
const agentNames = ['planner', 'generator', 'healer', 'assistant'];

let output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/embed-agents.js
 * Source files: src/mcp/agents/*.md
 *
 * Re-run "node scripts/embed-agents.js" after editing any agent .md file.
 * This file is automatically regenerated during "npm run build".
 */

`;

let embeddedCount = 0;

for (const name of agentNames) {
    const mdPath = path.join(agentsDir, `${name}.md`);
    if (fs.existsSync(mdPath)) {
        const content = fs.readFileSync(mdPath, 'utf-8');
        // Normalize line endings (Windows CRLF -> LF)
        const normalized = content.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
        // Escape for embedding in template literal: backticks, backslashes, ${} interpolation
        const escaped = normalized
            .replace(/\\/g, '\\\\')
            .replace(/`/g, '\\`')
            .replace(/\$\{/g, '\\${');
        output += `export const ${name}AgentContent = \`${escaped}\`;\n\n`;
        embeddedCount++;
    } else {
        console.warn(`  Warning: Agent file not found: ${mdPath}`);
        output += `export const ${name}AgentContent = '';\n\n`;
    }
}

// Export a lookup map for easy access
output += `export const AGENT_CONTENT: Record<string, string> = {\n`;
for (const name of agentNames) {
    output += `    ${name}: ${name}AgentContent,\n`;
}
output += `};\n\n`;

// Export the agent names list
output += `export const AGENT_NAMES = ${JSON.stringify(agentNames)} as const;\n`;

fs.writeFileSync(outputFile, output, 'utf-8');
console.log(`✅ Embedded ${embeddedCount} agent definitions into ${path.relative(process.cwd(), outputFile)}`);
