/**
 * CS Playwright Test Framework - Typed Fixtures Declaration
 * Auto-generated by: npx cs-playwright-test generate-fixtures
 *
 * This declaration file provides TypeScript IntelliSense support for page fixtures.
 * Keep importing from '@mdakhan.mak/cs-playwright-test-framework/spec' in your spec files.
 * TypeScript will automatically pick up these type augmentations.
 *
 * DO NOT EDIT MANUALLY - Regenerate when adding new pages:
 *   npx cs-playwright-test generate-fixtures --project=<your-project>
 *
 * Generated: 2025-12-26T11:46:30.149Z
 */

// Import page classes for type references
import { OrangeHRMDashboardPage } from './pages/OrangeHRMDashboardPage';
import { OrangeHRMLoginPage } from './pages/OrangeHRMLoginPage';

// Augment SpecFixtures interface with page types
declare module '@mdakhan.mak/cs-playwright-test-framework/spec' {
    interface SpecFixtures {
        dashboardPage: OrangeHRMDashboardPage;
        loginPage: OrangeHRMLoginPage;
    }
}
