/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/embed-skills.js
 * Source files: src/mcp/skills/<skill-name>/**
 *
 * Re-run "node scripts/embed-skills.js" after editing any skill file.
 * This file is automatically regenerated during "npm run build".
 */

export const SKILL_CONTENT: Record<string, Record<string, string>> = {
    'audit-rules': {
        'SKILL.md': `---
name: audit-rules
description: The canonical set of MANDATED rules every generated file must obey. Consumed by the cs-playwright-mcp audit_file tool. Load this skill before generating or reviewing any target file.
---

# CS Playwright Framework — MANDATED Rules

The \`audit_file\` MCP tool runs these rules deterministically. Any \`error\`-severity violation blocks the file from advancing to the commit-ready gate.

Rule IDs are stable — referenced by the healer, the generator, and escalation reports.

## Page-object rules (PO)

| ID | Severity | Rule |
|---|---|---|
| PO001 | error | Class decorated with \`@CSPage('<kebab-case-id>')\` |
| PO002 | error | Class extends \`CSBasePage\` (or \`CSFramePage\` if it has a \`frame\` property) |
| PO003 | error | Every \`CSWebElement\`-typed field has an \`@CSGetElement\` decorator |
| PO004 | error | \`@CSGetElement\` uses \`xpath:\` as primary locator (not \`id:\`, \`css:\`, or \`role:\` as primary) |
| PO005 | error | Every \`@CSGetElement\` has a \`description:\` string |
| PO006 | warn | Interactive elements (inputs, buttons, links, submits) have \`selfHeal: true\` |
| PO007 | error | No raw \`this.page.locator(...)\`, \`this.page.click(...)\`, \`this.page.fill(...)\` anywhere in the class |
| PO008 | error | Action methods use \`*WithTimeout\` variants, not bare \`click()\` / \`fill()\` |
| PO009 | warn | Navigation-triggering clicks use \`clickWithTimeout(30000)\` or higher |

## Step-definition rules (SD)

| ID | Severity | Rule |
|---|---|---|
| SD001 | error | Class has \`@StepDefinitions\` decorator |
| SD002 | error | Page injection via \`@Page('<kebab-key>')\` — no \`new PageName()\` anywhere |
| SD003 | error | Step decorator \`@CSBDDStepDef('<exact text>')\`; no other step decorator permitted |
| SD004 | error | Scenario-scoped state via \`CSBDDContext.getInstance()\` — no private class fields holding scenario data |
| SD005 | error | Each step body either calls \`CSReporter.pass(msg)\` on success, or calls \`CSReporter.fail(msg)\` followed by \`throw new Error(msg)\` — no silent return |
| SD006 | error | Config access via \`CSValueResolver.resolve('{config:<KEY>}', context)\` — no raw \`process.env\` |

## Feature-file rules (FF)

| ID | Severity | Rule |
|---|---|---|
| FF001 | error | Feature-level tags include a project tag + at least one module/feature-area tag |
| FF002 | error | Data-driven scenarios use \`Scenario Outline:\` + \`Examples:\` block with \`"type": "json"\` source |
| FF003 | error | \`Examples:\` filter clause uses \`scenarioId=<id> AND runFlag=Yes\` |
| FF004 | warn | Every scenario has at least 3 \`Then\`/\`And\` verification steps |

## Data-file rules (DF)

| ID | Severity | Rule |
|---|---|---|
| DF001 | error | Top-level JSON is an array of objects with at minimum \`{scenarioId, scenarioName, runFlag}\` |
| DF002 | error | No \`REPLACE_WITH_*\` placeholder values |
| DF003 | error | Every \`scenarioId\` in a feature file has a matching row in the data JSON |

## Helper / DB rules (DB)

| ID | Severity | Rule |
|---|---|---|
| DB001 | error | No inline SQL in pages or steps; every query resolves to a named entry in \`<project>-db-queries.env\` invoked via \`CSDBUtils.executeQuery(alias, queryName, params)\` |
| DB002 | error | Every query's \`schema.table.column\` is verified by \`schema_lookup\`; unresolved tables carry \`-- SCHEMA REFERENCE NEEDED\` sentinel |
| DB003 | error | DB helper methods are \`static\`, return typed interfaces (not \`any\`), handle case-tolerant column access (\`r.col ?? r.COL\`) |

## Cross-cutting rules (CC)

| ID | Severity | Rule |
|---|---|---|
| CC001 | error | No underscore separators in numeric literals — \`5000\` not \`5_000\` |
| CC002 | error | No application-source paths referenced in generated file comments (no \`/WEB-INF/\`, no upstream class names, no line-number citations) |
| CC003 | error | No \`console.log\` |
| CC004 | error | No bare \`expect(...)\` from \`@playwright/test\` |
| CC005 | error | Imports only from \`@mdakhan.mak/cs-playwright-test-framework/*\` subpaths or local files |
| CC006 | error | No \`TODO\`, \`FIXME\`, \`XXX\`, \`HACK\`, or \`PLACEHOLDER\` tokens |
| CC007 | error | No \`@pending\`, \`@skip\`, \`@wip\`, \`@ignore\` tags on shipped scenarios |

## How agents use this skill

- **Generator** loads this before drafting each file; runs through the rules mentally, then calls \`audit_file\` to verify deterministically
- **Healer** loads this before every proposed fix; audits the fix content before applying
- **Orchestrator** loads this at the commit-ready gate to verify the \`audit_file\` report is clean

The \`rules.yaml\` bundled alongside this SKILL.md is the machine-readable form of the same rule set, consumed directly by the \`audit_file\` tool.
`,
        'rules.yaml': `# Machine-readable audit rules consumed by the cs-playwright-mcp audit_file tool.
# Keep in sync with SKILL.md in this folder. Rule IDs are stable.
#
# Semantics of \`invertMatch\`:
#   - absent / false → required pattern: violation when regex has zero matches.
#   - true           → anti-pattern:     violation for each regex match.
#
# Rules with no \`detect\` field are semantic-only and are skipped by the
# regex engine (future TS-AST pass will handle them).

rules:
  # ========================================================================
  # Page-object rules (PO)
  # ========================================================================
  - id: PO001
    severity: error
    appliesTo: page
    description: "Class decorated with @CSPage('<kebab-case-id>')"
    detect: 'regex:@CSPage\\s*\\('
    violation: "Missing @CSPage decorator on page-object class"

  - id: PO002
    severity: error
    appliesTo: page
    description: "Class extends CSBasePage or CSFramePage"
    detect: 'regex:extends\\s+(CSBasePage|CSFramePage)'
    violation: "Page class must extend CSBasePage or CSFramePage"

  - id: PO003
    severity: error
    appliesTo: page
    description: "Every CSWebElement field has @CSGetElement decorator (semantic rule)"
    violation: "CSWebElement field declared without @CSGetElement"

  - id: PO004
    severity: error
    appliesTo: page
    description: "@CSGetElement uses xpath as primary locator (semantic rule)"
    violation: "@CSGetElement must use xpath as primary (CSS/role variants belong in alternativeLocators)"

  - id: PO005
    severity: error
    appliesTo: page
    description: "Every @CSGetElement has description (semantic rule)"
    violation: "@CSGetElement is missing description"

  - id: PO006
    severity: warn
    appliesTo: page
    description: "Interactive elements have selfHeal true (semantic rule)"
    violation: "Interactive element should enable selfHeal"

  - id: PO007
    severity: error
    appliesTo: page
    description: "No raw this.page.locator / click / fill / etc."
    detect: 'regex:this\\.page\\.(locator|click|fill|hover|press|check|uncheck|selectOption)\\s*\\('
    invertMatch: true
    violation: "Use decorated CSWebElement + CSWebElement methods, not raw this.page.* calls"

  - id: PO008
    severity: error
    appliesTo: page
    description: "Action methods use *WithTimeout variants (semantic rule)"
    violation: "Use clickWithTimeout / fillWithTimeout / etc., not bare click() or fill()"

  - id: PO009
    severity: warn
    appliesTo: page
    description: "Navigation-triggering clicks use 30000ms or higher (semantic rule)"
    violation: "clickWithTimeout on navigation should be >= 30000"

  # ========================================================================
  # Step-definition rules (SD)
  # ========================================================================
  - id: SD001
    severity: error
    appliesTo: step
    description: "Step class decorated with @StepDefinitions"
    detect: 'regex:@StepDefinitions\\b'
    violation: "Step class missing @StepDefinitions decorator"

  - id: SD002
    severity: error
    appliesTo: step
    description: "Page injection via @Page('<key>'); no new PageName()"
    detect: 'regex:new\\s+[A-Z]\\w*Page\\s*\\('
    invertMatch: true
    violation: "Use @Page('<key>') injection, not new PageName()"

  - id: SD003
    severity: error
    appliesTo: step
    description: "Step decorator @CSBDDStepDef"
    detect: 'regex:@CSBDDStepDef\\s*\\('
    violation: "Step missing @CSBDDStepDef decorator"

  - id: SD004
    severity: warn
    appliesTo: step
    description: "Scenario state via CSBDDContext.getInstance() (semantic rule)"
    violation: "Prefer CSBDDContext.getInstance() for scenario-scoped state; do not store on class fields"

  - id: SD005
    severity: error
    appliesTo: step
    description: "Steps end in pass OR fail+throw — no silent return (semantic rule)"
    violation: "Step must not silently return; pass or fail+throw required"

  - id: SD006
    severity: error
    appliesTo: step
    description: "Config access via CSValueResolver, not process.env"
    detect: 'regex:process\\.env\\.'
    invertMatch: true
    violation: "Use CSValueResolver.resolve('{config:KEY}', context), not process.env.KEY"

  # ========================================================================
  # Feature-file rules (FF)
  # ========================================================================
  - id: FF001
    severity: error
    appliesTo: feature
    description: "Feature has project tag plus at least one module tag"
    detect: 'regex:^@[\\w-]+\\s+@[\\w-]+'
    violation: "Feature must start with a project tag followed by at least one module tag"

  - id: FF002
    severity: error
    appliesTo: feature
    description: "Data-driven scenarios use JSON-sourced Examples"
    detect: 'regex:Examples:\\s*\\{[^}]*"type"\\s*:\\s*"json"'
    violation: "Scenario Outline must source Examples from JSON"

  - id: FF003
    severity: error
    appliesTo: feature
    description: "Examples filter includes scenarioId and runFlag=Yes"
    detect: 'regex:filter[^"]*"[^"]*scenarioId=[^"]*AND\\s+runFlag=Yes'
    violation: "Examples filter must include scenarioId=<id> AND runFlag=Yes"

  - id: FF004
    severity: warn
    appliesTo: feature
    description: "Every scenario has at least three verification steps (semantic rule)"
    violation: "Thin scenario — fewer than 3 verification Then/And steps"

  # ========================================================================
  # Data-file rules (DF)
  # ========================================================================
  - id: DF001
    severity: error
    appliesTo: data
    description: "Canonical scenarios JSON shape (semantic rule)"
    violation: "Data file must be an array of objects with scenarioId, scenarioName, and runFlag"

  - id: DF002
    severity: error
    appliesTo: data
    description: "No REPLACE_WITH_* placeholder values"
    detect: 'regex:REPLACE_WITH_'
    invertMatch: true
    violation: "Placeholder REPLACE_WITH_* present; populate the field or set runFlag to No"

  - id: DF003
    severity: error
    appliesTo: data
    description: "Every feature scenarioId has a matching data row (semantic rule)"
    violation: "scenarioId in feature has no matching data row"

  # ========================================================================
  # Helper / DB rules (DB)
  # ========================================================================
  - id: DB001
    severity: error
    appliesTo: helper
    description: "No inline SQL strings in helpers — use CSDBUtils named queries"
    detect: 'regex:"\\s*(SELECT|INSERT|UPDATE|DELETE)\\s'
    invertMatch: true
    violation: "Inline SQL in helper/page/step — use CSDBUtils.executeQuery with a named query in the env file"

  - id: DB002
    severity: error
    appliesTo: helper
    description: "Every SQL table must be verified via schema_lookup (semantic rule)"
    violation: "Unverified table — run schema_lookup; if absent, emit -- SCHEMA REFERENCE NEEDED"

  - id: DB003
    severity: error
    appliesTo: helper
    description: "Helpers are static with typed returns and case-tolerant row access (semantic rule)"
    violation: "Helper methods must be static, typed, and use r.col ?? r.COL"

  # ========================================================================
  # Cross-cutting rules (CC)
  # ========================================================================
  - id: CC001
    severity: error
    appliesTo: ts
    description: "Plain numeric literals — no underscore separators"
    detect: 'regex:\\b[0-9]+_[0-9]+\\b'
    invertMatch: true
    violation: "Underscore separator in numeric literal — use plain digits (e.g., 5000 not 5_000)"

  - id: CC002
    severity: error
    appliesTo: ts
    description: "No application-source paths referenced in generated files"
    detect: 'regex:/WEB-INF/|/src/main/(java|webapp|resources)/|\\.jsp["'']|\\.jspx["'']|\\.hbm\\.xml["'']'
    invertMatch: true
    violation: "Application-source path reference in generated file (e.g., /WEB-INF/, src/main/java/, *.jsp, *.hbm.xml). Generated test code must not cite upstream app source."

  - id: CC003
    severity: error
    appliesTo: ts
    description: "No console.log"
    detect: 'regex:\\bconsole\\.log\\s*\\('
    invertMatch: true
    violation: "console.log present — use CSReporter.info / CSReporter.debug"

  - id: CC004
    severity: error
    appliesTo: ts
    description: "No bare expect() from @playwright/test"
    detect: 'regex:\\bexpect\\s*\\('
    invertMatch: true
    violation: "Bare expect() — use CSReporter.fail then throw new Error, or a framework assertion helper"

  - id: CC005
    severity: error
    appliesTo: ts
    description: "Imports only from framework subpaths or local files (semantic rule)"
    violation: "Unsanctioned import path — use @mdakhan.mak/cs-playwright-test-framework/* or local relative paths only"

  - id: CC006
    severity: error
    appliesTo: ts,feature,data
    description: "No TODO / FIXME / XXX / HACK / PLACEHOLDER tokens"
    detect: 'regex:\\b(TODO|FIXME|XXX|HACK|PLACEHOLDER)\\b'
    invertMatch: true
    violation: "Placeholder / TODO token present — resolve before commit"

  - id: CC007
    severity: error
    appliesTo: feature
    description: "No @pending / @skip / @wip / @ignore tags on shipped scenarios"
    detect: 'regex:@(pending|skip|wip|ignore)\\b'
    invertMatch: true
    violation: "Skip / pending tag on shipped scenario — use runFlag: No in the data JSON instead"
`,
    },
    'commit-ready-9-gates': {
        'SKILL.md': `---
name: commit-ready-9-gates
description: The canonical 9-gate exit bar — every generated file must pass all nine before the pipeline advances to the per-file human-approval handoff.
---

# Commit-Ready Exit Bar — 9 Gates

A file reaches the "approve + migrate next" handoff only if every one of these gates passes. Miss any → escalation instead.

## The nine gates

| # | Gate | Check | Tool |
|---|---|---|---|
| 1 | Compile clean | \`tsc --noEmit\` produces zero errors for the generated file(s) | \`cs-playwright-mcp/compile_check\` |
| 2 | Audit clean | \`audit_file\` on every generated file returns zero \`error\`-severity violations | \`cs-playwright-mcp/audit_file\` |
| 3 | Tests green | Healer returned \`SUCCESS\`: every in-scope scenario green, baseline preserved, final full-suite re-run green | \`cs-playwright-mcp/test_run\` + Healer subagent |
| 4 | No placeholders | No \`TODO\`, \`FIXME\`, \`PLACEHOLDER\`, \`REPLACE_WITH_\`, \`XXX\`, \`HACK\` in any generated file | \`grep_search\` |
| 5 | No raw APIs | No \`console.log\`, \`page.locator(\`, \`from '@playwright/test'\` in any generated file | \`grep_search\` |
| 6 | SQL grounded | Every SQL string in a generated helper/step resolves to a registered entry in \`config/<project>/common/<project>-db-queries.env\` | verified by \`db-migrator\`; spot-check at gate |
| 7 | Imports resolve | Every \`import\` path in a generated file exists | \`compile_check\` catches this as a side-effect |
| 8 | Data matches | Every \`scenarioId\` in a generated feature file has a matching row in the corresponding \`_scenarios.json\`, and \`runFlag\` = \`Yes\` | \`commit_ready_check\` tool |
| 9 | No orphans | Every generated file the pipeline emitted is on disk and listed in the run summary; no files written then lost | \`commit_ready_check\` tool |

## How the check runs

At Stage 6 of the pipeline, the orchestrator calls:

\`\`\`
cs-playwright-mcp/commit_ready_check --files=<list>
\`\`\`

The tool returns:

\`\`\`json
{
  "ready": true | false,
  "gates": [
    { "id": 1, "name": "compile", "pass": true, "details": null },
    { "id": 2, "name": "audit", "pass": false, "details": {
        "violations": [{"file":"...","rule":"CC003","line":42,"message":"console.log present"}]
      }
    },
    ...
  ]
}
\`\`\`

If \`ready: true\` → orchestrator presents the three handoff buttons (approve + advance / rework / stop).

If \`ready: false\` → orchestrator writes an escalation report citing failing gates and halts with only the rework + stop buttons (no approve-and-advance option). The human must resolve before the pipeline continues.

## There is no partial-success

Gates are binary pass/fail. You do not get to advance with "8 of 9 green". The point of the bar is to guarantee that every approved file is truly commit-ready — no follow-up cleanup expected.
`,
    },
    'correction-memory-format': {
        'SKILL.md': `---
name: correction-memory-format
description: How to read and write the Healer's correction memory file — the system that makes the pipeline smarter over time.
---

# Correction memory

File: \`.agent-runs/correction-patterns.md\`

Content: a list of JSON blocks, each recording one verified fix pattern. Prepended with a heading. Appended to over time; never rewritten in place.

## Entry format

\`\`\`
## <hash> — <failureClass>

\`\`\`json
{
  "signature": "TimeoutError: locator did not match //button[@id=\\"signin-btn\\"]",
  "hash": "a3f7e12b4c5d8e9a",
  "failureClass": "LOW",
  "rootCause": "Element id changed from 'signin-btn' to testId 'loginSubmit'",
  "fixStrategy": "Updated @CSGetElement xpath primary to //button[@data-testid=\\"loginSubmit\\"]; retained old css form as last alternative",
  "verifiedGreen": true,
  "recordedAt": "2026-04-23T14:12:47.123Z",
  "examplePatch": "xpath: '//button[@id=\\"signin-btn\\"]' → xpath: '//button[@data-testid=\\"loginSubmit\\"]'"
}
\`\`\`

## Required fields

| Field | Type | Purpose |
|---|---|---|
| \`signature\` | string | Human-readable failure signature; use the error message with noise (timestamps, numeric ids, full paths) stripped |
| \`hash\` | string | 16-char SHA-256 prefix of \`signature\` — enables cheap exact lookups |
| \`failureClass\` | \`LOW\`/\`MEDIUM\`/\`HIGH\` | From \`classify_failure\` — HIGH entries are informational only (not auto-healed) |
| \`rootCause\` | string | Why it failed — one sentence |
| \`fixStrategy\` | string | Concise description of what the fix changed |
| \`verifiedGreen\` | boolean | **Must be true** — only verified-green fixes are recorded |
| \`recordedAt\` | ISO timestamp | When the entry was added |
| \`examplePatch\` | string (optional) | Before/after or other recoverable fix sketch |

## Lookup semantics

The \`correction_memory_query\` tool returns:

- **Exact hit** — entry with matching \`hash\` or exact-equal \`signature\`
- **Partial hits** — entries whose \`signature\` is a substring of the query (or vice versa), ranked by length overlap

Agents use exact hits first; partial hits are suggestions the LLM evaluates.

## Write rules

- **Only record on verified-green.** The \`correction_memory_record\` tool refuses to write when \`verifiedGreen: false\`
- **One entry per unique fix**. Don't record near-duplicates; the query will find the original by substring match
- **Redact sensitive values** — never put real user emails, real passwords, real test-env hostnames in the signature or fix strategy
- **Append-only** — existing entries are never rewritten; if a pattern becomes obsolete, add a new entry referencing the old hash in \`fixStrategy\`

## Human pruning

Over many runs the memory file grows. A maintainer may occasionally:
- Delete entries older than N months
- Merge near-duplicate entries into a single canonical one
- Archive environment-specific entries to \`.agent-runs/correction-patterns-archive.md\`

No tool does this automatically — the Healer only appends.
`,
    },
    'db-helper-case-tolerant': {
        'SKILL.md': `---
name: db-helper-case-tolerant
description: Use for every DB helper — case-tolerant column access, because Oracle and SQL Server drivers disagree on column-name case.
---

# Pattern: case-tolerant column access in DB helpers

## When to use

Every time you read a value from a DB result row, regardless of which database. Same pattern for single-row helpers, list helpers, count helpers.

## The rule

**Always** access via \`r.<lowerCase> ?? r.<UPPER_CASE>\`. Never write just \`r.user_id\` or just \`r.USER_ID\`.

## Why

- Oracle JDBC returns column names in UPPER_CASE by default
- Microsoft SQL Server and PostgreSQL drivers can return either case depending on driver config
- Framework test runs may switch databases; code that assumes one case breaks on the other
- The \`??\` nullish coalesce is free — one undefined access, no performance cost

## Example

\`\`\`typescript
return {
    id: r.id ?? r.ID,                       // ✓ tolerant
    userName: r.user_name ?? r.USER_NAME,   // ✓ tolerant
    lastLoginAt: r.last_login_at ?? r.LAST_LOGIN_AT,
    status: r.status ?? r.STATUS,
};
\`\`\`

NOT:

\`\`\`typescript
return {
    id: r.ID,                // ✗ fails on lower-case driver
    userName: r.user_name,   // ✗ fails on Oracle upper-case
};
\`\`\`

## Rules

- Every mapped field uses \`r.col ?? r.COL\`
- Number / boolean / date columns may still need conversion after the access (\`Number(...)\`, \`Boolean(...)\`, \`new Date(...)\`)
- If a column is legitimately case-mixed in source (rare), include both variants: \`r.firstName ?? r.first_name ?? r.FIRST_NAME\`
`,
    },
    'db-helper-findall-matching': {
        'SKILL.md': `---
name: db-helper-findall-matching
description: Use when authoring a database helper that returns a list of matching rows. Covers typed-array return, empty-array default, CSReporter logging.
---

# Pattern: DB helper — findAll (list)

## When to use

Any helper that returns zero-or-more rows for a given criterion — list of users with a role, list of active deals, list of payments in a status.

## Example

\`\`\`typescript
import { CSDBUtils } from '@mdakhan.mak/cs-playwright-test-framework/database-utils';
import { CSReporter } from '@mdakhan.mak/cs-playwright-test-framework/reporter';

export interface PaymentRow {
    paymentId: string;
    amount: number;
    status: string;
}

export class PaymentDatabaseHelper {
    private static readonly DB_ALIAS = 'my-project';

    public static async findPaymentsByStatus(status: string): Promise<PaymentRow[]> {
        const result = await CSDBUtils.executeQuery(
            this.DB_ALIAS,
            'PAYMENT_FIND_BY_STATUS',
            [status]
        );
        const rows = result.rows || [];
        CSReporter.info(\`Found \${rows.length} payments with status=\${status}\`);
        return rows.map((r: any) => ({
            paymentId: r.payment_id ?? r.PAYMENT_ID,
            amount: Number(r.amount ?? r.AMOUNT),
            status: r.status ?? r.STATUS,
        }));
    }
}
\`\`\`

Matching entry in \`<project>-db-queries.env\`:

\`\`\`
DB_QUERY_PAYMENT_FIND_BY_STATUS=SELECT PAYMENT_ID, AMOUNT, STATUS FROM PAYMENTS WHERE STATUS = :1
\`\`\`

## Rules

- Return \`Promise<RowType[]>\` — never \`Promise<any[]>\`
- Empty result → return \`[]\`, not \`null\`
- Always \`CSReporter.info(...)\` the count — surfaces in reports
- Map every row through explicit field extraction (case-tolerant: \`r.col ?? r.COL\`)
- Method is static; no constructor needed
`,
    },
    'db-helper-findby-id': {
        'SKILL.md': `---
name: db-helper-findby-id
description: Use when authoring a database helper method that reads a single row by id. Covers CSDBUtils.executeQuery, named-query reference, typed return, case-tolerant row access.
---

# Pattern: DB helper — findByX (single row)

## When to use

Any scenario preamble that needs to resolve a row from the test database before driving the UI. Common: "Given an active deal exists", "Given user with role X exists", "Given a payment in status Y exists".

## Example

\`\`\`typescript
import { CSDBUtils } from '@mdakhan.mak/cs-playwright-test-framework/database-utils';
import { CSReporter } from '@mdakhan.mak/cs-playwright-test-framework/reporter';

export interface UserRow {
    id: string;
    name: string;
    email: string;
    role: string;
}

export class UserDatabaseHelper {
    private static readonly DB_ALIAS = 'my-project';

    public static async findUserById(id: string): Promise<UserRow | null> {
        const result = await CSDBUtils.executeQuery(
            this.DB_ALIAS,
            'USER_FIND_BY_ID',
            [id]
        );
        const rows = result.rows || [];
        if (rows.length === 0) {
            CSReporter.info(\`No user found for id=\${id}\`);
            return null;
        }
        const r = rows[0] as any;
        return {
            id: r.id ?? r.ID,
            name: r.name ?? r.NAME,
            email: r.email ?? r.EMAIL,
            role: r.role ?? r.ROLE,
        };
    }

    public static async findUserByEmail(email: string): Promise<UserRow | null> {
        const result = await CSDBUtils.executeQuery(
            this.DB_ALIAS,
            'USER_FIND_BY_EMAIL',
            [email]
        );
        const rows = result.rows || [];
        if (rows.length === 0) return null;
        const r = rows[0] as any;
        return {
            id: r.id ?? r.ID,
            name: r.name ?? r.NAME,
            email: r.email ?? r.EMAIL,
            role: r.role ?? r.ROLE,
        };
    }
}
\`\`\`

And the matching entry in \`config/my-project/common/my-project-db-queries.env\`:

\`\`\`
DB_QUERY_USER_FIND_BY_ID=SELECT ID, NAME, EMAIL, ROLE FROM USERS WHERE ID = :1
DB_QUERY_USER_FIND_BY_EMAIL=SELECT ID, NAME, EMAIL, ROLE FROM USERS WHERE EMAIL = :1
\`\`\`

## Rules

- All helper methods are **\`static\`** — never instantiate the class
- Return a typed interface — \`Promise<UserRow | null>\`, never \`Promise<any>\`
- Null for single-row miss; empty array for list miss — never throw on empty
- Case-tolerant column access: \`r.col ?? r.COL\` for every field (Oracle/SQL Server drivers differ)
- The \`DB_ALIAS\` constant is the alias key from the pipeline config
- Query name is a **key** into the \`<project>-db-queries.env\` file — never inline SQL in the helper
- \`CSReporter.info(...)\` for empty-result logging (no fail, just note)
- Imports exclusively from \`@mdakhan.mak/cs-playwright-test-framework/*\`
- No raw \`console.log\`, no \`any\` return types, no string-concat SQL
`,
    },
    'ff-scenario-outline': {
        'SKILL.md': `---
name: ff-scenario-outline
description: Use when authoring a feature file with data-driven scenarios. Covers Scenario Outline + the JSON-sourced Examples block with filter syntax.
---

# Pattern: data-driven feature file with JSON Examples

## When to use

Any scenario that varies by data — different users, different inputs, different expected outcomes. The data lives in a sibling \`_scenarios.json\` file referenced from the \`Examples:\` block.

## Example

\`\`\`gherkin
@my-project @login @smoke
Feature: Login — authenticated user reaches the dashboard

  @TS_LOGIN_01
  Scenario Outline: Valid credentials redirect to dashboard
    When I navigate to the login page
    And I login as "<userName>" with password "<password>"
    Then I should see the dashboard welcome for "<userName>"
    And the dashboard header should be visible
    And the account switcher should be enabled

    Examples: {"type": "json", "source": "test/my-project/data/login/login_scenarios.json", "path": "$", "filter": "scenarioId=TS_LOGIN_01 AND runFlag=Yes"}
\`\`\`

And its sibling data file \`login_scenarios.json\`:

\`\`\`json
[
  {
    "scenarioId": "TS_LOGIN_01",
    "scenarioName": "Standard user logs in",
    "userName": "alice@example.com",
    "password": "ENC:{AES256}xxxxx",
    "runFlag": "Yes"
  }
]
\`\`\`

## Rules

- Feature-level tags: project tag (e.g., \`@my-project\`) + at least one module/area tag
- Scenario-level tag: the legacy test id (e.g., \`@TS_LOGIN_01\`) — preserve 1:1 with legacy, never rename
- \`Scenario Outline\` + \`Examples:\` (not plain \`Scenario\`) for data-driven tests
- \`Examples:\` block is a JSON object on one line with these keys:
  - \`"type": "json"\`
  - \`"source"\`: path relative to workspace root
  - \`"path"\`: JQ-style path into the file (usually \`"$"\` for root array)
  - \`"filter"\`: \`"scenarioId=<id> AND runFlag=Yes"\` — both clauses required
- Placeholders \`<fieldName>\` in steps must match JSON field names exactly
- Every scenario has at least 3 Then/And verification steps — thin scenarios (<3 verifications) are rejected by the audit
- No \`@pending\`, \`@skip\`, \`@wip\` tags on shipped scenarios — use \`runFlag: "No"\` in the JSON instead
`,
    },
    'ff-smoke-scenario': {
        'SKILL.md': `---
name: ff-smoke-scenario
description: Use when authoring a single non-data-driven scenario — smoke test, quick health check.
---

# Pattern: simple Scenario (not Outline)

## When to use

A scenario with no data variations — one fixed path, typically a smoke test or a single negative test. Use plain \`Scenario:\` not \`Scenario Outline:\`.

## Example

\`\`\`gherkin
@my-project @login @smoke
Feature: Login — basic smoke

  @TS_LOGIN_SMOKE
  Scenario: Login page loads and required fields are visible
    When I navigate to the application login page
    Then the user id input is visible
    And the password input is visible
    And the sign in button is enabled
\`\`\`

## Rules

- Feature-level tags: project + feature-area
- Scenario-level tag: legacy test id if this maps to one; otherwise a clear \`@<purpose>\` tag
- No \`Examples:\` block for plain \`Scenario:\`
- At least 3 Then/And verification steps (per audit rule FF004)
- Steps match step-definition text exactly
`,
    },
    'heal-cascade-revert': {
        'SKILL.md': `---
name: heal-cascade-revert
description: Use when a fix for one failing scenario breaks a previously-green scenario. Revert, reclassify, escalate.
---

# Healing pattern: cascade regression

## When to apply

The Healer applies a fix, re-runs the failing scenario (green), but the cascade check reports a previously-green scenario is now red. The fix introduced a regression elsewhere.

Classification of the original failure: was LOW or MEDIUM; the cascade event reclassifies it to HIGH.

## Contract

Cascade regression is **not** a second fix attempt — it's a **revert + escalate**. The Healer does not try a second fix that might break yet another scenario.

## Sequence

\`\`\`
1. baseline_green = snapshot of currently-passing scenarios (captured before the heal loop started)
2. fix applied; target scenario now green
3. cascade = test_run(baseline_green)
4. if any baseline_green scenario is now failing:
      a. revert the fix (restore the file from pre-fix state)
      b. re-run the target scenario to confirm it's back to its original failing state
      c. escalate with a structured report
      d. do NOT try another fix
      e. do NOT record the (failed) pattern to correction memory
\`\`\`

## What the escalation report includes

- Original failure id + signature
- Fix attempted (file edited, exact diff)
- Cascade scenarios that regressed (ids + new error messages)
- Classification: HIGH (cascade-induced)
- Recommendation: the original failure likely requires a broader refactor (e.g. page-object restructure, shared helper change) — beyond the Healer's single-file fix scope
- Pointer to where the human should look

## Example

Failing target: \`TS_LOGIN_01\`. Fix proposed: changed \`signInButton\` locator from \`//button[@id="signin-btn"]\` to \`//button[@data-testid="loginSubmit"]\`.

Cascade check: \`TS_PASSWORD_RESET_01\` (previously green) now fails with the same locator because it reuses the same \`LoginPage\`. The underlying DOM change affects both — but the generated fix only considered the target scenario's context.

Action: revert, escalate. Human needs to decide whether the page-object change is the right fix (which would update \`TS_PASSWORD_RESET_01\` too) or whether the UI change is unexpected and should be reverted in the app.

## Rules

- **Revert is mandatory** when cascade detected — do not ship a fix that regressed green scenarios
- Revert restores the exact pre-fix content — use \`read_file\` to snapshot before applying, then \`edit_file\` to restore on revert
- After revert, confirm the target scenario is again in its ORIGINAL failing state (sanity-check — if it now passes with no fix, the original failure may have been flaky, not deterministic)
- Never retry with a different fix after a cascade regression in the same loop — escalate and let a human judge
- The failed attempt is NOT recorded to correction memory (memory only records verified-green patterns)
`,
    },
    'heal-locator-drift': {
        'SKILL.md': `---
name: heal-locator-drift
description: Use when a test fails because an element locator no longer matches the DOM. The Healer uses this pattern to propose a targeted fix.
---

# Healing pattern: locator drift

## When to apply

Failure signatures:
- \`TimeoutError: locator.click: Locator did not match …\`
- \`Element not found for selector …\`
- \`Waiting for locator("…") failed: <timeout>\`

Classification: LOW.

## The diagnostic sequence

1. Call \`browser_snapshot\` on the failing page to capture the live accessibility tree
2. Find the element that semantically matches the failing locator's description
3. Call \`browser_generate_locator\` on that element — get ranked strategies (testId > role+name > label > text > id > css)
4. Call \`correction_memory_query\` with the failure signature — if a prior fix for a similar drift exists, prefer its strategy
5. Propose the fix: update \`@CSGetElement\` in the page object with the new primary xpath + carry old value into \`alternativeLocators\` as a fallback

## Example fix (before → after)

Before — locator stopped matching:
\`\`\`typescript
@CSGetElement({
    xpath: '//button[@id="signin-btn"]',
    description: 'Sign In submit button',
    selfHeal: true,
})
public signInButton!: CSWebElement;
\`\`\`

Live snapshot reveals: element now has \`data-testid="loginSubmit"\` and role \`button\` with name \`Sign in\`. The old \`id="signin-btn"\` was removed.

After — fix preserves the old form as a fallback and uses testId-based xpath primary:
\`\`\`typescript
@CSGetElement({
    xpath: '//button[@data-testid="loginSubmit"]',
    description: 'Sign In submit button',
    selfHeal: true,
    alternativeLocators: [
        'css:[data-testid="loginSubmit"]',
        'role:button|name:Sign in',
        'css:button#signin-btn',    // old form, kept as final fallback
    ],
})
public signInButton!: CSWebElement;
\`\`\`

## Rules

- **xpath primary** — if the ranked strategy is role-based, wrap it: \`//button[@data-testid="loginSubmit"]\`
- **Preserve the old locator** in \`alternativeLocators\` as the last entry — helps if the change was partial / reverted
- **Audit before apply** — the proposed fix must pass \`audit_file\` (still xpath-primary, still selfHeal true on interactive elements)
- **Compile before re-run** — \`compile_check\` must remain clean
- **Cascade-check after re-run** — other scenarios using the same page object must still pass
- **Record on green** — call \`correction_memory_record\` with the signature + fix strategy once the final full-suite re-run is green
`,
    },
    'heal-timing-flaky': {
        'SKILL.md': `---
name: heal-timing-flaky
description: Use when a test fails intermittently with timing / visibility errors — action fires before the page has rendered or settled.
---

# Healing pattern: timing flakiness

## When to apply

Failure signatures:
- \`Element is not visible\` / \`Element is not attached to DOM\` (but IS visible on re-run)
- \`Navigation timeout exceeded\`
- \`waitForLoadState\` timeouts
- Intermittent \`Element is detached\`

Classification: LOW.

## Root causes in priority order

1. **Action fired before page settled** — e.g., click happens while a navigation is still in-flight
2. **Element waits for AJAX** but test proceeds on first paint
3. **Animation / transition** — button is visible but not yet interactive
4. **Implicit default timeout too short** for server round-trip clicks

## Diagnostic sequence

1. Re-run the failing scenario alone — confirm flakiness (passes sometimes)
2. Check the action method — is there an explicit \`waitForVisible\` before the action?
3. Check the click's timeout — is it 5000 on a navigation-triggering click?
4. Check if there's a loading overlay that wasn't awaited

## Fix variants

### Variant A — raise the click timeout

\`\`\`typescript
// Before
await this.submitButton.clickWithTimeout(5000);

// After — navigation-triggering click
await this.submitButton.clickWithTimeout(30000);
\`\`\`

### Variant B — add an explicit readiness wait

\`\`\`typescript
public async submitAndWait(): Promise<void> {
    await this.submitButton.waitForVisible(10000);
    await this.submitButton.clickWithTimeout(30000);
    await this.page.waitForLoadState('networkidle');
}
\`\`\`

### Variant C — wait for a loading overlay to disappear

\`\`\`typescript
public async submit(): Promise<void> {
    await this.submitButton.clickWithTimeout(30000);
    await this.loadingOverlay.waitForHidden(30000);   // explicit overlay wait
}
\`\`\`

### Variant D — wait for the NEXT page's anchor element

\`\`\`typescript
// Prefer this — actionable vs. arbitrary sleep
public async submitAndExpectDashboard(): Promise<void> {
    await this.submitButton.clickWithTimeout(30000);
    const dashboard = new DashboardPage(this.browserManager);
    await dashboard.pageTitle.waitForVisible(30000);
}
\`\`\`

## Rules

- **Never** use \`this.page.waitForTimeout(N)\` as a fix — that's a band-aid, not a solution. The audit may allow it as a warning, but it's the wrong approach
- Raise specific element timeouts rather than blanket increasing the default
- Prefer waiting for the next meaningful element over waiting for "the page to settle"
- If flakiness persists after a correct fix, the failure is no longer LOW — reclassify and escalate
`,
    },
    'ir-and-session-state': {
        'SKILL.md': `---
name: ir-and-session-state
description: Canonical JSON shapes for the intermediate representation (IR) shared between agents and the orchestrator session state file.
---

# IR (intermediate representation)

Analyzer produces IR. Every downstream agent reads IR. Shape is stable across source languages.

\`\`\`json
{
  "source": {
    "path": "<absolute path | URL>",
    "language": "java | csharp | html-dom",
    "test_runner": "testng | junit4 | junit5 | nunit | xunit | greenfield",
    "ui_library": "selenium | webdriver.io | playwright-legacy",
    "hash": "sha256-<16 hex chars>"
  },
  "tests": [
    {
      "id": "TC_001",
      "name": "valid login",
      "description": "optional",
      "tags": ["@smoke", "@login"],
      "legacy_metadata": { "original_id": "TS_4482", "priority": "P1" },
      "data_refs": [
        { "key": "userName", "source_file": "test-data/users.xlsx", "sheet": "Users", "row_key": "TC_001" }
      ],
      "steps": [
        { "action": "navigate", "target": { "type": "config", "key": "BASE_URL" } },
        { "action": "click",    "element": { "field": "signInButton" } },
        { "action": "fill",     "element": { "field": "userIdField" }, "value": "$data.userName" },
        { "action": "assert_text", "element": { "field": "welcomeHeader" }, "expected": "Welcome" }
      ],
      "db_ops": [
        {
          "type": "select",
          "sql_raw": "SELECT id, name FROM users WHERE email = ?",
          "params": ["$userEmail"],
          "suggested_name": "USER_FIND_BY_EMAIL",
          "return_shape": "single-row"
        }
      ]
    }
  ],
  "page_objects": [
    {
      "name": "LoginPage",
      "screen_hint": "login",
      "elements": [
        { "field": "userIdField", "locator_type": "id", "value": "userId", "description": "User Id input" }
      ]
    }
  ],
  "summary": {
    "test_count": 1,
    "data_file_count": 1,
    "db_op_count": 1,
    "parse_confidence": "high | medium | low"
  }
}
\`\`\`

## Enriched IR (after Locator Reconciler)

Every element gains:
\`\`\`json
{
  "field": "userIdField",
  "description": "User Id input",
  "primary": { "locator_type": "xpath", "value": "//input[@id=\\"userId\\"]", "confidence": 95 },
  "alternatives": ["css:input#userId", "role:textbox|name:User Id"],
  "source": "live-DOM | memory | source-only",
  "selfHeal": true,
  "waitForVisible": true
}
\`\`\`

# Session state

\`.agent-runs/session-<runId>.json\`:

\`\`\`json
{
  "runId": "2026-04-23T14-02-11-a7f3",
  "project": "my-project",
  "mode": "migration | greenfield",
  "processed": ["LoginTest.java"],
  "approved": ["LoginTest.java"],
  "rejected": [],
  "pending": ["LogoutTest.java", "PasswordResetTest.java"],
  "currentStage": "GATE | RUNNING | AWAITING_USER_APPROVAL | IDLE",
  "correctionPatternsApplied": [],
  "_createdAt": "...",
  "_updatedAt": "..."
}
\`\`\`

## Rules

- Every agent reads IR; no agent re-parses source
- \`source.hash\` lets downstream agents cache — same hash → same IR, reuse
- Empty arrays, not nulls, for no-data cases (\`data_refs: []\`, \`db_ops: []\`)
- Agents mutate nothing in-place; they return enriched copies
- Session state is shallow-merged on every update (\`state_write\` semantics)
`,
    },
    'legacy-example-csharp-nunit': {
        'SKILL.md': `---
name: legacy-example-csharp-nunit
description: Reference — a representative C# + NUnit test class + page object. Agents pattern-match against this when parsing similar legacy files.
---

# Reference: typical C# + NUnit legacy test

Use this skill when \`legacy_parse\` encounters a C# + NUnit source file.

## Typical test class

\`\`\`csharp
using NUnit.Framework;
using OpenQA.Selenium;
using Example.Pages;

namespace Example.Tests
{
    [TestFixture]
    public class LoginTests : BaseTest
    {
        private LoginPage loginPage;
        private DashboardPage dashboardPage;

        [SetUp]
        public void SetUp()
        {
            loginPage = new LoginPage(driver);
            dashboardPage = new DashboardPage(driver);
        }

        [Test]
        [TestCase("alice@example.com", "Welcome, Alice")]
        [TestCase("bob@example.com",   "Welcome, Bob")]
        public void LoginSuccessTest(string userName, string expectedHeader)
        {
            driver.Navigate().GoToUrl("https://app.example.com/login");
            loginPage.EnterUserName(userName);
            loginPage.EnterPassword("ENC:passwd");
            loginPage.ClickSignIn();

            var header = dashboardPage.GetWelcomeHeader();
            Assert.AreEqual(expectedHeader, header);
        }
    }
}
\`\`\`

## Typical page object

\`\`\`csharp
using OpenQA.Selenium;
using OpenQA.Selenium.Support.PageObjects;

namespace Example.Pages
{
    public class LoginPage
    {
        [FindsBy(How = How.Id, Using = "userId")]
        private IWebElement userIdField;

        [FindsBy(How = How.Id, Using = "password")]
        private IWebElement passwordField;

        [FindsBy(How = How.XPath, Using = "//button[@id='signin-btn']")]
        private IWebElement signInButton;

        public LoginPage(IWebDriver driver) { PageFactory.InitElements(driver, this); }

        public void EnterUserName(string userName) { userIdField.SendKeys(userName); }
        public void EnterPassword(string password) { passwordField.SendKeys(password); }
        public void ClickSignIn() { signInButton.Click(); }
    }
}
\`\`\`

## What \`legacy_parse\` extracts

- **Runner**: detected as \`nunit\` from \`using NUnit.Framework\`
- **Tests**: \`LoginSuccessTest\` with its \`[TestCase]\` rows becoming \`data_refs\` (inlined)
- **Steps**: navigate, fill, fill, click, assert
- **Page objects**: same as Java — \`[FindsBy]\` translates to the IR element list
- **DB ops**: if any inline \`new SqlCommand("SELECT ...")\` constructions, they go to \`extract_db_calls\`

## Variations

- \`[Fact]\` instead of \`[Test]\` → xUnit runner
- \`[Theory]\` with \`[InlineData]\` → data-provider equivalent
- \`WebDriverWait\` usage → translates to \`waitForVisible\` in IR steps
- Ginq/LINQ assertions (\`Assert.That(x, Is.EqualTo(y))\`) → same assert_equals semantics
`,
    },
    'legacy-example-java-testng': {
        'SKILL.md': `---
name: legacy-example-java-testng
description: Reference — a representative Java + TestNG test class + page object. Agents pattern-match against this when parsing similar legacy files.
---

# Reference: typical Java + TestNG legacy test

Use this skill when \`legacy_parse\` encounters a Java + TestNG source file and the agent needs to sanity-check the parsed IR against the shape of real-world legacy code.

## Typical test class

\`\`\`java
package com.example.tests;

import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import org.testng.annotations.DataProvider;
import org.openqa.selenium.WebDriver;
import com.example.pages.LoginPage;
import com.example.pages.DashboardPage;

public class LoginTest extends BaseTest {

    private LoginPage loginPage;
    private DashboardPage dashboardPage;

    @BeforeMethod
    public void setUp() {
        loginPage = new LoginPage(driver);
        dashboardPage = new DashboardPage(driver);
    }

    @DataProvider(name = "users")
    public Object[][] provideUsers() {
        return new Object[][] {
            { "alice@example.com", "Welcome, Alice" },
            { "bob@example.com",   "Welcome, Bob" }
        };
    }

    @Test(dataProvider = "users")
    public void loginSuccessTest(String userName, String expectedHeader) {
        driver.get("https://app.example.com/login");
        loginPage.enterUserName(userName);
        loginPage.enterPassword("ENC:passwd");
        loginPage.clickSignIn();

        String header = dashboardPage.getWelcomeHeader();
        assertEquals(expectedHeader, header);
    }

    @Test
    public void lockedAccountTest() {
        String sql = "SELECT LOCK_STATUS FROM USERS WHERE EMAIL = '" + "locked@example.com" + "'";
        // ...
    }
}
\`\`\`

## Typical page object

\`\`\`java
package com.example.pages;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;

public class LoginPage {

    @FindBy(id = "userId")
    private WebElement userIdField;

    @FindBy(id = "password")
    private WebElement passwordField;

    @FindBy(xpath = "//button[@id='signin-btn']")
    private WebElement signInButton;

    public LoginPage(WebDriver driver) { PageFactory.initElements(driver, this); }

    public void enterUserName(String userName) { userIdField.sendKeys(userName); }
    public void enterPassword(String password) { passwordField.sendKeys(password); }
    public void clickSignIn() { signInButton.click(); }
}
\`\`\`

## What \`legacy_parse\` extracts

- **Tests**: \`loginSuccessTest\`, \`lockedAccountTest\` (each with step sequence: navigate, fill, fill, click, assert)
- **Data refs**: the \`@DataProvider\` method — inlined rows (in this case)
- **Page objects**: \`LoginPage\` with elements \`userIdField\` (id=userId), \`passwordField\` (id=password), \`signInButton\` (xpath=…)
- **DB ops**: the inline SELECT in \`lockedAccountTest\` — goes to \`extract_db_calls\` for migration

## Variations seen in the wild

- \`@FindBy(css = ...)\` in place of \`@FindBy(xpath = ...)\`
- \`@BeforeClass\` instead of \`@BeforeMethod\`
- \`@Test(groups = {...})\` — treat as tag metadata
- Inline locators: \`driver.findElement(By.id("userId"))\` — extract as a dynamic locator in IR
`,
    },
    'legacy-example-jdbc-inline-sql': {
        'SKILL.md': `---
name: legacy-example-jdbc-inline-sql
description: Reference — common legacy inline-SQL patterns in Java / C# so extract_db_calls can identify them and the agent can sanity-check the migration plan.
---

# Reference: common inline-SQL patterns in legacy code

Use when \`extract_db_calls\` returns a plan and the agent needs to verify that the extraction caught the right strings.

## Pattern 1 — raw JDBC with string concatenation

\`\`\`java
String userId = row.get("userId");
String sql = "SELECT ID, NAME FROM USERS WHERE ID = " + userId;
PreparedStatement stmt = conn.prepareStatement(sql);
ResultSet rs = stmt.executeQuery();
\`\`\`

\`extract_db_calls\` emits:
\`\`\`
suggestedName: USERS_SELECT_01
parameterised: SELECT ID, NAME FROM USERS WHERE ID = :1
params: [userId]
returnShape: list   // SELECT without LIMIT 1 / ROWNUM <= 1
table: USERS
\`\`\`

## Pattern 2 — PreparedStatement with \`?\` placeholders

\`\`\`java
String sql = "UPDATE PAYMENTS SET STATUS = ? WHERE ID = ?";
PreparedStatement stmt = conn.prepareStatement(sql);
stmt.setString(1, newStatus);
stmt.setString(2, paymentId);
stmt.executeUpdate();
\`\`\`

\`extract_db_calls\` emits:
\`\`\`
suggestedName: PAYMENTS_UPDATE_01
parameterised: UPDATE PAYMENTS SET STATUS = :1 WHERE ID = :2
params: [newStatus, paymentId]
returnShape: void
table: PAYMENTS
\`\`\`

## Pattern 3 — Hibernate HQL

\`\`\`java
Query query = session.createQuery(
    "FROM User u WHERE u.role = :role AND u.active = true"
);
query.setParameter("role", "ACCOUNT_REP");
List<User> users = query.list();
\`\`\`

Hibernate HQL is harder — \`extract_db_calls\` can identify the string but the migration plan notes "HQL, not SQL — map entity to table before registering as named query".

## Pattern 4 — Inline assertion against query result

\`\`\`java
String sql = "SELECT COUNT(*) FROM USERS WHERE EMAIL = 'locked@example.com'";
int count = conn.createStatement().executeQuery(sql).getInt(1);
assertEquals(1, count);
\`\`\`

\`extract_db_calls\` emits:
\`\`\`
suggestedName: USERS_COUNT_BY_EMAIL
parameterised: SELECT COUNT(*) FROM USERS WHERE EMAIL = :1
params: ['locked@example.com']    // literal extracted
returnShape: single-row
table: USERS
\`\`\`

## What the agent does with the plan

1. For each entry, call \`schema_lookup\` against the \`table\` field
2. If verified → add \`DB_QUERY_<name>=<parameterised>\` to \`<project>-db-queries.env\`
3. If unverified → emit \`-- SCHEMA REFERENCE NEEDED\` sentinel and escalate
4. Generate a typed helper method (via \`db-helper-findby-id\` / \`db-helper-findall-matching\` patterns)
5. Replace the original call site in the generated TS file with a helper invocation

## What to watch for

- Heredoc / multi-line SQL (\`"""..."""\` in Kotlin, verbatim strings in C#) — some may slip through regex extraction
- Dynamic SQL built via string manipulation — may need manual review and rewrite
- Stored procedure calls — treat as a separate migration pattern (named SP execution, not a SELECT)
`,
    },
    'named-query-env-entry': {
        'SKILL.md': `---
name: named-query-env-entry
description: Use when adding a SQL query to the project's db-queries env file. Covers naming, parameterisation, and comment conventions.
---

# Pattern: named query in \`<project>-db-queries.env\`

## When to use

Every SQL query the test suite runs lives in this file. Helpers invoke them by name via \`CSDBUtils.executeQuery(alias, queryName, params)\`.

## File location

\`config/<project>/common/<project>-db-queries.env\`

## Example

\`\`\`
# ----------------------------------------------------------------------------
# Users
# ----------------------------------------------------------------------------

DB_QUERY_USER_FIND_BY_ID=SELECT ID, NAME, EMAIL, ROLE FROM USERS WHERE ID = :1

DB_QUERY_USER_FIND_BY_EMAIL=SELECT ID, NAME, EMAIL, ROLE FROM USERS WHERE LOWER(EMAIL) = LOWER(:1)

DB_QUERY_USER_FIND_ACTIVE_BY_ROLE=SELECT ID, NAME, EMAIL, ROLE FROM USERS WHERE ROLE = :1 AND ACTIVE_FLAG = 'Y' AND ROWNUM <= 10

# ----------------------------------------------------------------------------
# Payments
# ----------------------------------------------------------------------------

DB_QUERY_PAYMENT_FIND_BY_STATUS=SELECT PAYMENT_ID, AMOUNT, STATUS FROM PAYMENTS WHERE STATUS = :1
\`\`\`

## Rules

- Key format: \`DB_QUERY_<ENTITY>_<VERB>_[<QUALIFIER>]\` all UPPER_SNAKE_CASE
- Verb one of: \`FIND_BY_<FIELD>\`, \`FIND_ALL_<QUALIFIER>\`, \`COUNT_BY_<FIELD>\`, \`INSERT\`, \`UPDATE_<FIELD>\`, \`DELETE_BY_<FIELD>\`
- Bind parameters use \`:1\`, \`:2\`, \`:3\` (1-indexed) — never inline string values
- Each SQL must have been verified via \`schema_lookup\` against the project schema reference
- Never fabricate table names; if unverified, mark with \`-- SCHEMA REFERENCE NEEDED\` and escalate
- Group by entity with a comment header — makes the file browseable as it grows
- Never leave commented-out queries — delete instead
`,
    },
    'po-click-action-method': {
        'SKILL.md': `---
name: po-click-action-method
description: Use when authoring a click action on a page object. Covers clickWithTimeout with the correct long-timeout convention for navigation-triggering clicks.
---

# Pattern: click action method

## When to use

Any method on a page object that performs a click — navigation link, submit button, row link, tab switch. Separate waits + assertions into their own methods.

## Example

\`\`\`typescript
public async clickSignIn(): Promise<void> {
    await this.signInButton.waitForVisible(10000);
    await this.signInButton.clickWithTimeout(30000);   // nav click — long budget
    CSReporter.info('Clicked Sign In');
}

public async clickRowByIndex(index: number): Promise<void> {
    await this.resultsRows.waitForVisible(10000);
    const cells = await this.resultsRows.locator(\`xpath=//tbody/tr[\${index + 1}]\`);
    await cells.click();
    CSReporter.info(\`Clicked row \${index}\`);
}
\`\`\`

## Rules

- Use \`clickWithTimeout(30000)\` or higher for clicks that trigger page load or server round-trip. Short timeouts (5000) are only safe for purely-client-side controls
- Always \`waitForVisible\` before the click — eliminates a class of timing flakes
- Call \`CSReporter.info(...)\` so the click appears in the test report
- Never use bare \`click()\` — always the \`*WithTimeout\` variant
- Never call \`this.page.click(...)\` directly
`,
    },
    'po-dynamic-element': {
        'SKILL.md': `---
name: po-dynamic-element
description: Use when an element must be located at runtime (loop index, row number, dynamic label). Covers CSElementFactory for runtime element construction.
---

# Pattern: runtime-built element via CSElementFactory

## When to use

The locator depends on test-time data — e.g., "the row whose first cell contains \`<userName>\`", "the Nth result", "the button labelled \`<scenario.action>\`". Static \`@CSGetElement\` decorators can't express this. Use \`CSElementFactory.createByXPath\` in an action method.

## Example

\`\`\`typescript
import { CSBasePage, CSPage, CSGetElement } from '@mdakhan.mak/cs-playwright-test-framework/core';
import { CSWebElement, CSElementFactory } from '@mdakhan.mak/cs-playwright-test-framework/element';
import { CSReporter } from '@mdakhan.mak/cs-playwright-test-framework/reporter';

@CSPage('results-grid')
export class ResultsGridPage extends CSBasePage {

    @CSGetElement({
        xpath: '//table[@id="results"]',
        description: 'Results grid',
        waitForVisible: true,
    })
    public grid!: CSWebElement;

    public async clickRowByLabel(label: string): Promise<void> {
        const escaped = label.replace(/'/g, "\\\\'");
        const row = CSElementFactory.createByXPath(
            \`//table[@id="results"]//tr[td[normalize-space(text())='\${escaped}']]//a[1]\`,
            \`Results row: \${label}\`,
            this.page
        );
        await row.clickWithTimeout(30000);
        CSReporter.info(\`Clicked row labelled: \${label}\`);
    }
}
\`\`\`

## Rules

- \`CSElementFactory.createByXPath(xpath, description, this.page)\` — description is required, shows in logs
- Always escape user-supplied strings in xpath (\`'\` → \`\\\\'\`)
- Prefer static \`@CSGetElement\` when possible — reserve factory for genuinely dynamic cases
- The returned element has the same \`*WithTimeout\` surface as decorated elements
- For navigation clicks, still use 30000+ timeout
`,
    },
    'po-fill-action-method': {
        'SKILL.md': `---
name: po-fill-action-method
description: Use when authoring a fill / type action on a page object. Covers clear + fillWithTimeout sequence.
---

# Pattern: fill action method

## When to use

Any method that types into an input. The standard sequence is wait → clear → fill → optional reporter line.

## Example

\`\`\`typescript
public async enterUserName(userName: string): Promise<void> {
    await this.userIdField.waitForVisible(10000);
    await this.userIdField.clearWithTimeout(5000);
    await this.userIdField.fillWithTimeout(userName, 5000);
    CSReporter.info(\`Entered user id: \${userName}\`);
}

public async enterCredentials(userName: string, password: string): Promise<void> {
    await this.enterUserName(userName);
    await this.passwordField.clearWithTimeout(5000);
    await this.passwordField.fillWithTimeout(password, 5000);
    CSReporter.info('Credentials entered');
}
\`\`\`

## Rules

- Always clear before fill — prevents residue from prior values
- Use \`fillWithTimeout\`, not bare \`fill()\`
- Never log the raw password value; log a redacted marker if needed (\`CSReporter.info('Password entered (redacted)')\`)
- Short timeouts (5000) are fine — fill is purely client-side
`,
    },
    'po-frame-element': {
        'SKILL.md': `---
name: po-frame-element
description: Use when the page content lives inside one or more nested iframes. Covers CSFramePage with single-frame string and nested-frame array forms.
---

# Pattern: elements inside iframes

## When to use

The target screen's content is rendered inside an \`<iframe>\` — e.g., an embedded third-party widget, a rich-text editor iframe, or a legacy webform embedded in a host app. Any \`@CSGetElement\` on the page needs the frame context applied.

## Example — single iframe

\`\`\`typescript
import { CSFramePage, CSPage, CSGetElement } from '@mdakhan.mak/cs-playwright-test-framework/core';
import { CSWebElement } from '@mdakhan.mak/cs-playwright-test-framework/element';
import { CSReporter } from '@mdakhan.mak/cs-playwright-test-framework/reporter';

@CSPage('payment-widget')
export class PaymentWidgetPage extends CSFramePage {

    // All elements declared below inherit this frame context
    protected frame = { title: 'Payment Gateway' };

    @CSGetElement({
        xpath: '//input[@name="cardNumber"]',
        description: 'Card Number input',
        waitForVisible: true,
        selfHeal: true,
        alternativeLocators: ['css:input[name="cardNumber"]'],
    })
    public cardNumberInput!: CSWebElement;

    @CSGetElement({
        xpath: '//button[@type="submit"]',
        description: 'Submit payment',
        waitForVisible: true,
        selfHeal: true,
        alternativeLocators: ['text:Pay'],
    })
    public submitButton!: CSWebElement;

    public async pay(cardNumber: string): Promise<void> {
        await this.waitForFrameReady();
        await this.cardNumberInput.fillWithTimeout(cardNumber, 5000);
        await this.submitButton.clickWithTimeout(30000);
        CSReporter.pass('Payment submitted');
    }
}
\`\`\`

## Example — nested iframes

\`\`\`typescript
@CSPage('deep-editor')
export class DeepEditorPage extends CSFramePage {

    // Frame chain: outermost -> innermost. Strategies may be freely mixed.
    protected frame = [
        { id: 'appShell' },
        { name: 'workspaceFrame' },
        { title: 'Document Editor' },
    ];

    @CSGetElement({
        xpath: '//textarea[@id="body"]',
        description: 'Document body textarea',
        waitForVisible: true,
        selfHeal: true,
    })
    public bodyArea!: CSWebElement;
}
\`\`\`

## Frame selector options

The \`frame\` property accepts either a single descriptor or an array of descriptors (outer to inner):

- String: \`'//iframe[@title="Editor"]'\` (xpath auto-detected), \`'#frameId'\` (css)
- Object with one of: \`{ xpath, css, id, name, title, testId, src, index }\`

## Rules

- Extend \`CSFramePage\` (NOT \`CSBasePage\`) when any element on the page lives inside an iframe
- \`frame\` is a \`protected\` class field, not a decorator option
- For nested frames, order the array outermost-first
- Call \`this.waitForFrameReady()\` before the first interaction
- All other page-object rules apply (xpath primary, selfHeal on interactive, descriptions, *WithTimeout methods)
`,
    },
    'po-self-healing-element': {
        'SKILL.md': `---
name: po-self-healing-element
description: Use when declaring an interactive element (input, button, link, submit, checkbox, combobox) on a page object. Adds selfHeal + alternativeLocators for resilient locator fallback.
---

# Pattern: self-healing interactive element

## When to use

Any element the user clicks, types into, or selects. Buttons, inputs, submit controls, links, checkboxes, select dropdowns. Not needed for purely read labels or headers.

## Example

\`\`\`typescript
import { CSBasePage, CSPage, CSGetElement } from '@mdakhan.mak/cs-playwright-test-framework/core';
import { CSWebElement } from '@mdakhan.mak/cs-playwright-test-framework/element';
import { CSReporter } from '@mdakhan.mak/cs-playwright-test-framework/reporter';

@CSPage('login-form')
export class LoginFormPage extends CSBasePage {

    @CSGetElement({
        xpath: '//input[@id="userId"]',
        description: 'User Id input',
        waitForVisible: true,
        selfHeal: true,
        alternativeLocators: [
            'css:input#userId',
            'css:input[name="userId"]',
        ],
    })
    public userIdField!: CSWebElement;

    @CSGetElement({
        xpath: '//input[@id="password"]',
        description: 'Password input',
        waitForVisible: true,
        selfHeal: true,
        alternativeLocators: ['css:input#password', 'css:input[type="password"]'],
    })
    public passwordField!: CSWebElement;

    @CSGetElement({
        xpath: '//button[@id="signin-btn"]',
        description: 'Sign In submit button',
        waitForVisible: true,
        selfHeal: true,
        alternativeLocators: ['css:button#signin-btn', 'text:Sign In'],
    })
    public signInButton!: CSWebElement;

    protected initializeElements(): void {
        CSReporter.debug('LoginFormPage elements initialized');
    }

    public async login(userName: string, password: string): Promise<void> {
        await this.userIdField.waitForVisible(10000);
        await this.userIdField.clearWithTimeout(5000);
        await this.userIdField.fillWithTimeout(userName, 5000);
        await this.passwordField.clearWithTimeout(5000);
        await this.passwordField.fillWithTimeout(password, 5000);
        await this.signInButton.clickWithTimeout(30000);
        CSReporter.pass(\`Login submitted for \${userName}\`);
    }
}
\`\`\`

## Rules

- \`xpath\` is primary; css/text variants go in \`alternativeLocators\`
- \`selfHeal: true\` on every interactive element
- \`description\` required
- For navigation-triggering clicks, use \`clickWithTimeout(30000)\` or higher — short timeouts time out on server-round-trip clicks
- Action methods call \`*WithTimeout\` variants, never bare \`click()\` / \`fill()\`
- On success call \`CSReporter.pass(msg)\`; on failure call \`CSReporter.fail(msg)\` then \`throw new Error(msg)\`
- Plain numeric literals — \`30000\` not \`30_000\`
- No \`this.page.click(...)\` or \`this.page.locator(...)\` — everything goes through the decorated element
`,
    },
    'po-simple-element': {
        'SKILL.md': `---
name: po-simple-element
description: Use when declaring a passive (non-interactive) element on a page object — labels, headers, read-only fields. Covers @CSGetElement with xpath primary + description + waitForVisible.
---

# Pattern: simple passive element on a page object

## When to use

Any read-only element: page title, section heading, displayed status label, badge, static text. No click, no fill, no type — the test only reads its text or verifies its visibility.

## Example

\`\`\`typescript
import { CSBasePage, CSPage, CSGetElement } from '@mdakhan.mak/cs-playwright-test-framework/core';
import { CSWebElement } from '@mdakhan.mak/cs-playwright-test-framework/element';
import { CSReporter } from '@mdakhan.mak/cs-playwright-test-framework/reporter';

@CSPage('order-confirmation')
export class OrderConfirmationPage extends CSBasePage {

    @CSGetElement({
        xpath: '//h1[@id="order-title"]',
        description: 'Order confirmation page title',
        waitForVisible: true,
    })
    public pageTitle!: CSWebElement;

    @CSGetElement({
        xpath: '//span[@data-testid="order-status"]',
        description: 'Order status badge',
    })
    public orderStatus!: CSWebElement;

    protected initializeElements(): void {
        CSReporter.debug('OrderConfirmationPage elements initialized');
    }

    public async verifyTitle(expected: string): Promise<void> {
        await this.pageTitle.waitForVisible(15000);
        const actual = (await this.pageTitle.textContentWithTimeout(5000)) ?? '';
        if (actual.trim() !== expected) {
            const msg = \`Title mismatch: expected "\${expected}", got "\${actual.trim()}"\`;
            CSReporter.fail(msg);
            throw new Error(msg);
        }
        CSReporter.pass(\`Page title is "\${expected}"\`);
    }
}
\`\`\`

## Rules

- \`xpath\` is always the primary locator
- \`description\` is required (human-readable, appears in logs)
- \`waitForVisible: true\` on elements that must be present when the page is considered loaded
- \`selfHeal\` is NOT needed for passive elements — save it for interactive ones
- Use \`*WithTimeout\` variants of CSWebElement methods, never bare versions
- Plain numeric literals — \`15000\` not \`15_000\`
`,
    },
    'po-wait-and-verify-method': {
        'SKILL.md': `---
name: po-wait-and-verify-method
description: Use when authoring a verification / assertion method on a page object. Covers waitForVisible + textContent + strict pass/fail pattern.
---

# Pattern: wait + verify method

## When to use

Any page-object method whose purpose is to assert the UI has reached an expected state — title correct, value displayed, item present.

## Example

\`\`\`typescript
public async verifyTitle(expected: string): Promise<void> {
    await this.pageTitle.waitForVisible(15000);
    const actual = (await this.pageTitle.textContentWithTimeout(5000)) ?? '';
    const normalised = actual.replace(/\\s+/g, ' ').trim();
    if (normalised !== expected) {
        const msg = \`Title mismatch: expected "\${expected}", got "\${normalised}"\`;
        CSReporter.fail(msg);
        throw new Error(msg);
    }
    CSReporter.pass(\`Title is "\${expected}"\`);
}

public async verifyElementVisible(description: string, element: CSWebElement): Promise<void> {
    const visible = await element.isVisibleWithTimeout(10000);
    if (!visible) {
        const msg = \`\${description} not visible after 10s\`;
        CSReporter.fail(msg);
        throw new Error(msg);
    }
    CSReporter.pass(\`\${description} is visible\`);
}
\`\`\`

## Rules

- \`waitForVisible\` BEFORE reading text — avoids reading from an element still rendering
- Normalise whitespace with \`replace(/\\s+/g, ' ').trim()\` to avoid false negatives from stray newlines
- On failure: \`CSReporter.fail(msg)\` then \`throw new Error(msg)\` — same message string
- On success: \`CSReporter.pass(msg)\` — report reflects the verified state
- Never use bare \`expect(...)\` from \`@playwright/test\`
`,
    },
    'reporter-fail-and-throw': {
        'SKILL.md': `---
name: reporter-fail-and-throw
description: Use on any failure path in a step or page-object method. Covers the mandatory CSReporter.fail + throw Error pattern — never silent return, never raw expect.
---

# Pattern: failure path — \`CSReporter.fail(msg)\` then \`throw new Error(msg)\`

## When to use

Any place your code detects a condition that means the test has failed. Assertion mismatch, missing value, unexpected state, timeout on a required element. The pattern is always the same.

## Example

\`\`\`typescript
import { CSReporter } from '@mdakhan.mak/cs-playwright-test-framework/reporter';

export class DashboardPage extends CSBasePage {

    @CSGetElement({
        xpath: '//h1[@id="dashboard-title"]',
        description: 'Dashboard title',
        waitForVisible: true,
    })
    public pageTitle!: CSWebElement;

    public async verifyOnDashboard(): Promise<void> {
        const expected = 'Dashboard';
        await this.pageTitle.waitForVisible(15000);
        const actual = (await this.pageTitle.textContentWithTimeout(5000)) ?? '';
        const normalised = actual.trim();
        if (normalised !== expected) {
            const msg = \`Dashboard title mismatch: expected "\${expected}", got "\${normalised}"\`;
            CSReporter.fail(msg);
            throw new Error(msg);
        }
        CSReporter.pass(\`On Dashboard ("\${expected}")\`);
    }
}
\`\`\`

## Success path — always \`CSReporter.pass(msg)\`

\`\`\`typescript
// After an action verified to have succeeded
CSReporter.pass('User successfully logged in');
\`\`\`

## Info / debug — for non-assertion logging

\`\`\`typescript
// For progress, not a pass/fail judgement
CSReporter.info('Attempting login for user: ' + userName);
CSReporter.debug('Cache hit for LoginForm page elements');
\`\`\`

## Rules

- **Every assertion path** either ends with \`CSReporter.pass(msg)\` or \`CSReporter.fail(msg); throw new Error(msg);\` — no silent return
- Error message passed to \`CSReporter.fail()\` and to \`new Error()\` is the **same string** — report reader sees the same text the test runner sees
- \`CSReporter.fail()\` alone is not enough — you must \`throw\` too. The \`fail\` call logs; the throw stops execution
- **No \`expect(...)\`** from \`@playwright/test\` — the framework's reporter owns assertions
- **No \`console.log\`** — use \`CSReporter.info()\` or \`CSReporter.debug()\`
- Error messages are actionable: include the expected and actual values, the element description, the scenario id if known
`,
    },
    'reporter-pass-on-success': {
        'SKILL.md': `---
name: reporter-pass-on-success
description: Use on every success path. CSReporter.pass with a specific, actionable message that surfaces in the HTML report.
---

# Pattern: report success with \`CSReporter.pass\`

## When to use

Every page-object method / step-def / helper that reaches its happy-path end state should end with a \`CSReporter.pass(msg)\` call. The test runner's HTML report is built from these messages.

## Example

\`\`\`typescript
public async approvePayment(paymentId: string): Promise<void> {
    await this.approveButton.waitForVisible(10000);
    await this.approveButton.clickWithTimeout(30000);
    await this.confirmationBanner.waitForVisible(15000);
    const banner = (await this.confirmationBanner.textContentWithTimeout(5000)) ?? '';
    if (!banner.includes('approved')) {
        const msg = \`Expected approval confirmation, got: \${banner}\`;
        CSReporter.fail(msg);
        throw new Error(msg);
    }
    CSReporter.pass(\`Payment \${paymentId} approved — banner: "\${banner.trim()}"\`);
}
\`\`\`

## What makes a good pass message

- **Specific**: include the entity id, the expected outcome, any verified value
- **Past-tense / verified**: "Payment X approved", "Dashboard opened", not "Clicking button"
- **Actionable on failure**: when the test later fails elsewhere, a good pass message in the report tells the debugger what worked
- **Short**: one line, < ~120 chars

## Rules

- Pair every pass with a guarded condition — don't blanket-log pass without verifying
- If you wouldn't be confident telling the user the step succeeded, don't call \`pass\`
- Never log raw secrets (passwords, tokens) — redact or omit
- Use \`CSReporter.info(...)\` for mid-flight progress updates (typing, clicking) and reserve \`pass\` for end-state confirmation
`,
    },
    'scenarios-json-row': {
        'SKILL.md': `---
name: scenarios-json-row
description: Use when authoring or updating a _scenarios.json data file. Covers canonical array shape, required fields, runFlag semantics, and the no-placeholder rule.
---

# Pattern: canonical scenarios JSON shape

## When to use

Every feature file has a matching \`<feature>_scenarios.json\`. Its shape is fixed — do not improvise.

## Example

\`\`\`json
[
  {
    "scenarioId": "TS_LOGIN_01",
    "scenarioName": "Standard user logs in successfully",
    "userName": "alice@example.com",
    "expectedDashboardHeader": "Welcome, Alice",
    "runFlag": "Yes"
  },
  {
    "scenarioId": "TS_LOGIN_02",
    "scenarioName": "Locked account shows error banner",
    "userName": "locked@example.com",
    "expectedErrorMessage": "Account locked after too many attempts",
    "runFlag": "Yes"
  },
  {
    "scenarioId": "TS_LOGIN_03",
    "scenarioName": "Password reset redirect flow",
    "runFlag": "No",
    "notes": "Pending: reset-email flow needs test-inbox access"
  }
]
\`\`\`

## Shape rules

- Top-level is a JSON **array** \`[ ... ]\`, not an object
- Every row has:
  - \`scenarioId\` (string) — matches the feature file \`filter:\` clause
  - \`scenarioName\` (string) — human-readable summary
  - \`runFlag\` (string, \`"Yes"\` or \`"No"\`)
- Other keys are scenario fields — camelCase, matching the \`<placeholders>\` in the feature steps exactly
- A row with \`runFlag: "No"\` may also carry a \`notes\` field explaining why — helps reviewers

## Forbidden values

- **No \`REPLACE_WITH_*\` placeholders anywhere.** A row with unresolved values is set to \`runFlag: "No"\` with a \`notes\` field, not shipped with a bogus placeholder
- No \`TODO\`, \`FIXME\`, \`XXX\`, \`PLACEHOLDER\`
- No empty required fields — if a field is unknown, omit the row (don't ship \`"userName": ""\`)

## Relationship with the feature file

- The feature's \`Examples:\` \`filter\` clause (\`scenarioId=<id> AND runFlag=Yes\`) matches exactly one row with the named id and \`Yes\` flag
- A feature with N \`Scenario Outline:\` blocks may reference N different filters in one data file, or N data files
- Every \`scenarioId\` in the feature must exist in the data file, and every row marked \`Yes\` should correspond to a feature-file scenario
`,
    },
    'sd-simple-step': {
        'SKILL.md': `---
name: sd-simple-step
description: Use when authoring a basic step definition with a single page injection and a single action.
---

# Pattern: simple step definition

## When to use

A step that calls one method on one page object. No parameter interpolation, no context variables, no DB lookups.

## Example

\`\`\`gherkin
When I click the Sign In button
\`\`\`

\`\`\`typescript
import { CSBDDStepDef, Page, StepDefinitions } from '@mdakhan.mak/cs-playwright-test-framework/bdd';
import { LoginFormPage } from '../../pages/login/LoginFormPage';

@StepDefinitions
export class LoginSteps {

    @Page('login-form')
    private loginPage!: LoginFormPage;

    @CSBDDStepDef('I click the Sign In button')
    async clickSignIn(): Promise<void> {
        await this.loginPage.clickSignIn();
    }
}
\`\`\`

## Rules

- Class decorated \`@StepDefinitions\`
- Page injection via \`@Page('<kebab-key>')\` — match the \`@CSPage('...')\` key on the page object
- Step text in the decorator matches the \`.feature\` text **exactly** (case, whitespace, punctuation)
- The step body delegates to a page-object method; it does not manipulate elements directly
- The page method already calls \`CSReporter.pass\`/\`fail\` — no duplicate logging in the step
`,
    },
    'sd-step-with-config': {
        'SKILL.md': `---
name: sd-step-with-config
description: Use when a step needs an environment or configuration value — BASE_URL, API_KEY, test user email. CSValueResolver, never process.env.
---

# Pattern: step definition reading config

## When to use

Any step that depends on environment config — URLs, feature flags, shared credentials, service endpoints.

## Example

\`\`\`typescript
import {
    CSBDDStepDef,
    Page,
    StepDefinitions,
    CSBDDContext,
} from '@mdakhan.mak/cs-playwright-test-framework/bdd';
import { CSValueResolver } from '@mdakhan.mak/cs-playwright-test-framework/utilities';
import { CSReporter } from '@mdakhan.mak/cs-playwright-test-framework/reporter';
import { LoginFormPage } from '../../pages/login/LoginFormPage';

@StepDefinitions
export class NavigationSteps {

    @Page('login-form')
    private loginPage!: LoginFormPage;

    private context = CSBDDContext.getInstance();

    @CSBDDStepDef('I navigate to the application login page')
    async openLogin(): Promise<void> {
        const baseUrl = CSValueResolver.resolve('{config:BASE_URL}', this.context);
        if (!baseUrl) {
            const msg = 'BASE_URL is not configured for this environment';
            CSReporter.fail(msg);
            throw new Error(msg);
        }
        const loginUrl = \`\${baseUrl}/login\`;
        await this.loginPage.navigate(loginUrl);
        CSReporter.pass(\`Opened login at \${loginUrl}\`);
    }
}
\`\`\`

## Rules

- Config access ONLY via \`CSValueResolver.resolve('{config:KEY}', context)\` — never \`process.env.KEY\`
- Resolved value might be empty/undefined — ALWAYS check before use; fail loudly if missing
- Config keys map to \`config/<project>/environments/<env>.env\` entries at runtime
- For encrypted values, the framework decrypts automatically when accessed via \`{config:…}\`
`,
    },
    'sd-step-with-context': {
        'SKILL.md': `---
name: sd-step-with-context
description: Use when a step needs to pass data to another step in the same scenario — e.g., capturing an id from a "Given …" to consume in a "Then …".
---

# Pattern: passing data between steps via CSBDDContext

## When to use

A scenario where step 1 discovers or creates a value (a generated id, a resolved entity key, a timestamp) that step 3 needs to reference. Use \`CSBDDContext\` — scenario-scoped, automatically cleared at end of scenario.

## Example

\`\`\`gherkin
Given I resolve an active deal from the database
When I open the asset search for the resolved deal
Then the deal key is shown in the header
\`\`\`

\`\`\`typescript
import {
    CSBDDStepDef,
    Page,
    StepDefinitions,
    CSBDDContext,
} from '@mdakhan.mak/cs-playwright-test-framework/bdd';
import { CSReporter } from '@mdakhan.mak/cs-playwright-test-framework/reporter';
import { AssetSearchPage } from '../../pages/assets/AssetSearchPage';
import { DealDatabaseHelper } from '../../helpers/DealDatabaseHelper';

@StepDefinitions
export class AssetSearchSteps {

    @Page('asset-search')
    private searchPage!: AssetSearchPage;

    private context = CSBDDContext.getInstance();

    @CSBDDStepDef('I resolve an active deal from the database')
    async resolveActiveDeal(): Promise<void> {
        const deal = await DealDatabaseHelper.findFirstActiveDeal();
        if (!deal) {
            const msg = 'No active deal found in the test database';
            CSReporter.fail(msg);
            throw new Error(msg);
        }
        this.context.setVariable('resolvedDealKey', deal.dealKey);
        CSReporter.pass(\`Resolved active deal: \${deal.dealKey}\`);
    }

    @CSBDDStepDef('I open the asset search for the resolved deal')
    async openAssetSearchForResolvedDeal(): Promise<void> {
        const dealKey = this.context.getVariable('resolvedDealKey') as string;
        if (!dealKey) {
            const msg = 'resolvedDealKey not set on scenario context';
            CSReporter.fail(msg);
            throw new Error(msg);
        }
        await this.searchPage.searchByDealKey(dealKey);
        CSReporter.pass(\`Asset search executed for \${dealKey}\`);
    }

    @CSBDDStepDef('the deal key is shown in the header')
    async verifyDealKeyInHeader(): Promise<void> {
        const dealKey = this.context.getVariable('resolvedDealKey') as string;
        await this.searchPage.verifyHeaderContainsDealKey(dealKey);
    }
}
\`\`\`

## Rules

- \`CSBDDContext.getInstance()\` is singleton-per-scenario — use the single \`this.context\` on the class
- \`setVariable(key, value)\` — write
- \`getVariable(key) as T\` — read, always cast to the expected type
- Missing values must be checked and fail loudly — never pass \`undefined\` downstream silently
- Do NOT store data in private class fields — the class is shared across scenarios, state will leak
- Preferred keys are camelCase, descriptive (\`resolvedDealKey\`, not \`d\`)
`,
    },
    'sd-step-with-db-precondition': {
        'SKILL.md': `---
name: sd-step-with-db-precondition
description: Use when a Given step resolves data from the database before driving UI — "Given a user with role X exists".
---

# Pattern: step definition with DB precondition

## When to use

Self-sufficient scenarios whose setup requires real database state (role lookup, active deal lookup, existing entity resolution). The step queries DB, stores the result on scenario context, then later steps consume it.

## Example

\`\`\`gherkin
Given an active user with role "ACCOUNT_REP" exists
When I login as the resolved user
Then the account rep dashboard opens
\`\`\`

\`\`\`typescript
import {
    CSBDDStepDef,
    Page,
    StepDefinitions,
    CSBDDContext,
} from '@mdakhan.mak/cs-playwright-test-framework/bdd';
import { CSReporter } from '@mdakhan.mak/cs-playwright-test-framework/reporter';
import { UserDatabaseHelper } from '../../helpers/UserDatabaseHelper';
import { LoginFormPage } from '../../pages/login/LoginFormPage';

@StepDefinitions
export class AuthSetupSteps {

    @Page('login-form')
    private loginPage!: LoginFormPage;

    private context = CSBDDContext.getInstance();

    @CSBDDStepDef('an active user with role {string} exists')
    async resolveActiveUserWithRole(role: string): Promise<void> {
        const user = await UserDatabaseHelper.findFirstActiveUserWithRole(role);
        if (!user) {
            const msg = \`No active user with role \${role} in the test database\`;
            CSReporter.fail(msg);
            throw new Error(msg);
        }
        this.context.setVariable('resolvedUser', user);
        CSReporter.pass(\`Resolved user: \${user.email} (\${role})\`);
    }

    @CSBDDStepDef('I login as the resolved user')
    async loginAsResolved(): Promise<void> {
        const user = this.context.getVariable('resolvedUser') as { email: string };
        if (!user) {
            const msg = 'resolvedUser not set on scenario context';
            CSReporter.fail(msg);
            throw new Error(msg);
        }
        await this.loginPage.login(user.email, /* password via VDI hook */ '');
    }
}
\`\`\`

## Rules

- DB access ONLY via a helper method — never inline SQL in the step
- If the expected row isn't found, fail loudly — do NOT create the row with an INSERT (DB writes are out of scope per project policy)
- Store the resolved entity on \`CSBDDContext\` under a descriptive key (\`resolvedUser\`, not \`u\`)
- Downstream steps read the same key and fail if unset
`,
    },
    'sd-step-with-params': {
        'SKILL.md': `---
name: sd-step-with-params
description: Use when a step captures parameters from the scenario — {string}, {int}, {float}.
---

# Pattern: step definition with parameters

## When to use

Any step whose feature-file text contains \`<placeholders>\` (Scenario Outline) or quoted values that the step body must receive.

## Example

\`\`\`gherkin
When I login as "<userName>" with password "<password>"
Then I should see a welcome message for "<userName>"
\`\`\`

\`\`\`typescript
@CSBDDStepDef('I login as {string} with password {string}')
async login(userName: string, password: string): Promise<void> {
    await this.loginPage.login(userName, password);
}

@CSBDDStepDef('I should see a welcome message for {string}')
async verifyWelcome(userName: string): Promise<void> {
    await this.dashboardPage.verifyWelcomeFor(userName);
}
\`\`\`

## Supported parameter types

- \`{string}\` — matches \`"..."\` or \`'...'\` in the step text
- \`{int}\` — matches \`\\d+\`, delivered as \`number\`
- \`{float}\` — matches \`\\d+\\.\\d+\`, delivered as \`number\`
- \`{word}\` — matches a single word (no spaces)

## Rules

- The parameter order in the method signature matches the \`{...}\` order in the step text
- Every parameter has a TypeScript type — never \`any\`
- Do NOT embed values directly in the decorator string — always use parameters
- Feature-file values map to these via Cucumber expression rules — no custom regex required
`,
    },
    'xlsx-multi-row-per-id': {
        'SKILL.md': `---
name: xlsx-multi-row-per-id
description: Use when a legacy xlsx sheet has multiple data rows per test id (variant rows). Covers flattening into scenarioId suffixes.
---

# Pattern: xlsx with multi-row-per-id shape (variants)

## When to use

Some legacy test-data sheets pack variant data under a single test id — e.g., one "smoke test" runs with three different users, three rows under the same \`TS_LOGIN_01\` id. \`data_parse\` handles this by flattening variants into distinct \`scenarioId\` entries.

## The input shape

Source sheet:

| scenarioId | scenarioName | userName | expectedOutcome | runFlag |
|---|---|---|---|---|
| TS_LOGIN_VARIANTS | Login variant 1 | alice@example.com | Welcome, Alice | Yes |
|   |   (empty)       | bob@example.com  | Welcome, Bob   | Yes |
|   |   (empty)       | charlie@example.com | Welcome, Charlie | Yes |
| TS_LOGOUT_01 | Logout | any@example.com | Goodbye | Yes |

Rows 2–3 share row 1's id because \`scenarioId\` is blank (variant continuation).

## How the flattening works

\`data_parse\` produces:

\`\`\`json
[
  { "scenarioId": "TS_LOGIN_VARIANTS",    "scenarioName": "Login variant 1",
    "userName": "alice@example.com",   "expectedOutcome": "Welcome, Alice",   "runFlag": "Yes" },
  { "scenarioId": "TS_LOGIN_VARIANTS-v2", "scenarioName": "Login variant 1",
    "userName": "bob@example.com",     "expectedOutcome": "Welcome, Bob",     "runFlag": "Yes" },
  { "scenarioId": "TS_LOGIN_VARIANTS-v3", "scenarioName": "Login variant 1",
    "userName": "charlie@example.com", "expectedOutcome": "Welcome, Charlie", "runFlag": "Yes" },
  { "scenarioId": "TS_LOGOUT_01",         "scenarioName": "Logout",
    "userName": "any@example.com",     "expectedOutcome": "Goodbye",          "runFlag": "Yes" }
]
\`\`\`

## Feature-file consumption

The \`Examples:\` filter now uses OR to include all variants:

\`\`\`
filter: "(scenarioId=TS_LOGIN_VARIANTS OR scenarioId=TS_LOGIN_VARIANTS-v2 OR scenarioId=TS_LOGIN_VARIANTS-v3) AND runFlag=Yes"
\`\`\`

Or simpler — glob prefix:

\`\`\`
filter: "scenarioId~TS_LOGIN_VARIANTS AND runFlag=Yes"
\`\`\`

(Depending on framework filter parser support.)

## Rules

- Blank \`scenarioId\` = continuation of previous row's id with suffix \`-vN\` (N starting at 2)
- \`scenarioName\` is inherited from the first variant row unless the variant has its own
- All fields default-inherit the first row's values for any blank cell in the variant
- The flattened output is always the canonical scenarios shape — downstream code treats each variant as a first-class scenario
`,
    },
    'xlsx-sheet-to-scenarios': {
        'SKILL.md': `---
name: xlsx-sheet-to-scenarios
description: Use when converting a legacy Excel sheet into a scenarios JSON file. One sheet → one scenarios JSON.
---

# Pattern: xlsx sheet → scenarios JSON (flat shape)

## When to use

Legacy projects typically ship a single \`.xlsx\` file with one sheet per feature / module. Each row is one test case. The tool \`data_parse\` auto-detects xlsx and emits canonical scenarios JSON.

## How the mapping works

- **First row** of the sheet = header = becomes JSON field names (camelCased)
- **Subsequent rows** = scenarios
- Column recognised as \`scenarioId\` (or \`testId\`, \`tcId\`, \`id\`) supplies \`scenarioId\`
- Column \`runFlag\` / \`run\` supplies \`runFlag\` ("Yes" or "No")
- Missing \`scenarioId\` → auto-generated \`TC_001\`, \`TC_002\`, ...

## Example

Source sheet:

| scenarioId | scenarioName | userName | expectedHeader | runFlag |
|---|---|---|---|---|
| TS_LOGIN_01 | Standard login | alice@example.com | Welcome, Alice | Yes |
| TS_LOGIN_02 | Locked account | locked@example.com | Account locked | Yes |
| TS_LOGIN_03 | Pending reset | reset@example.com | Reset email sent | No |

\`data_parse\` invocation:

\`\`\`
data_parse(path: "test-data/login.xlsx")
\`\`\`

Output JSON:

\`\`\`json
[
  { "scenarioId": "TS_LOGIN_01", "scenarioName": "Standard login",
    "userName": "alice@example.com", "expectedHeader": "Welcome, Alice", "runFlag": "Yes" },
  { "scenarioId": "TS_LOGIN_02", "scenarioName": "Locked account",
    "userName": "locked@example.com", "expectedHeader": "Account locked", "runFlag": "Yes" },
  { "scenarioId": "TS_LOGIN_03", "scenarioName": "Pending reset",
    "userName": "reset@example.com", "expectedHeader": "Reset email sent", "runFlag": "No" }
]
\`\`\`

## Rules

- One sheet → one JSON scenarios file (unless multi-row-per-id shape, see \`xlsx-multi-row-per-id\`)
- Sheet headers become camelCase keys (\`User Name\` → \`userName\`, \`Expected Header\` → \`expectedHeader\`)
- Empty cells → missing keys in the JSON (not empty string), so agents can reason about optional fields
- No \`REPLACE_WITH_*\` values ever — if a cell is known-incomplete, set \`runFlag: No\`
- Re-running \`data_parse\` on the same xlsx should be idempotent (deterministic ordering)
`,
    },
};

export const SKILL_NAMES: readonly string[] = ["audit-rules","commit-ready-9-gates","correction-memory-format","db-helper-case-tolerant","db-helper-findall-matching","db-helper-findby-id","ff-scenario-outline","ff-smoke-scenario","heal-cascade-revert","heal-locator-drift","heal-timing-flaky","ir-and-session-state","legacy-example-csharp-nunit","legacy-example-java-testng","legacy-example-jdbc-inline-sql","named-query-env-entry","po-click-action-method","po-dynamic-element","po-fill-action-method","po-frame-element","po-self-healing-element","po-simple-element","po-wait-and-verify-method","reporter-fail-and-throw","reporter-pass-on-success","scenarios-json-row","sd-simple-step","sd-step-with-config","sd-step-with-context","sd-step-with-db-precondition","sd-step-with-params","xlsx-multi-row-per-id","xlsx-sheet-to-scenarios"] as const;
